language: node_js

node_js:
  - '0.8'
  - '0.10'

env:
  - NODE_ENV=test

services:
  - mongodb

before_script:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g bower grunt-cli'

after_success: 'make coveralls'